### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [talmobi/looks-same-plus#1]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by talmobi** [comment]
Sure. Mostly this just wraps around https://github.com/gemini-testing/looks-same , though.

**Comment by geopic** [comment]
Doesn't harm to add one anyway. :smile: I'll start on it now.
